# Generated by Django 6.0.5 on 2026-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://c.ndtvimg.com/2023-07/c7hjbhmg_restaurant_625x300_29_July_23.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=675')),
                ('cusine', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
